#
# Module manifest for module 'PS-CsvUtil'
#
# Generated by: Santiago Squarzon
#
# Generated on: 10/16/2022
#

@{
    RootModule    = 'PS-CSVUtil.psm1'
    ModuleVersion = '1.0.0'
    GUID          = '6d13bed0-f461-4b73-9bdd-f5d01146a01c'
    Author        = 'Santiago Squarzon'
    CompanyName   = 'Unknown'
    Copyright     = '(c) Santiago Squarzon. All rights reserved.'
    Description   = 'tiny module to split and merge large Csv files.'
    PowerShellVersion      = '5.1'
    DotNetFrameworkVersion = '4.0'
    FunctionsToExport = 'Merge-Csv', 'Split-Csv'
    CmdletsToExport   = @()
    VariablesToExport = ''
    AliasesToExport   = ''
    PrivateData = @{
        PSData = @{
            Tags = @('csv', 'split', 'merge', 'powershell', 'streamreader', 'streamwriter')
        }
    }
}